// GET
export const FETCH_FARM_START = "FETCH_FARM_START";
export const FETCH_FARM_SUCCESS = "FETCH_FARM_SUCCESS";
export const FETCH_FARM_FAILURE = "FETCH_FARM_FAILURE";

export const FETCH_PUMP_START = "FETCH_PUMP_START";
export const FETCH_PUMP_SUCCESS = "FETCH_PUMP_SUCCESS";
export const FETCH_PUMP_FAILURE = "FETCH_PUMP_FAILURE";

export const FETCH_VALVE_START = "FETCH_VALVE_START";
export const FETCH_VALVE_SUCCESS = "FETCH_VALVE_SUCCESS";
export const FETCH_VALVE_FAILURE = "FETCH_VALVE_FAILURE";

// POST
export const ADD_FARM_START = "POST_FARM_START";
export const ADD_FARM_SUCCESS = "POST_FARM_SUCCESS";
export const ADD_FARM_FAILURE = "POST_FARM_FAILURE";

export const ADD_PUMP_START = "POST_PUMP_START";
export const ADD_PUMP_SUCCESS = "POST_PUMP_SUCCESS";
export const ADD_PUMP_FAILURE = "POST_PUMP_FAILURE";

export const ADD_VALVE_START = "POST_VALVE_START";
export const ADD_VALVE_SUCCESS = "POST_VALVE_SUCCESS";
export const ADD_VALVE_FAILURE = "POST_VALVE_FAILURE";

// PUT
export const UPDATE_FARM_START = "UPDATE_FARM_START";
export const UPDATE_FARM_SUCCESS = "UPDATE_FARM_SUCCESS";
export const UPDATE_FARM_FAILURE = "UPDATE_FARM_FAILURE";

export const UPDATE_PUMP_START = "UPDATE_PUMP_START";
export const UPDATE_PUMP_SUCCESS = "UPDATE_PUMP_SUCCESS";
export const UPDATE_PUMP_FAILURE = "UPDATE_PUMP_FAILURE";

export const UPDATE_VALVE_START = "UPDATE_VALVE_START";
export const UPDATE_VALVE_SUCCESS = "UPDATE_VALVE_SUCCESS";
export const UPDATE_VALVE_FAILURE = "UPDATE_VALVE_FAILURE";

// DELETE
export const DELETE_FARM_START = "DELETE_FARM_START";
export const DELETE_FARM_SUCCESS = "DELETE_FARM_SUCCESS";
export const DELETE_FARM_FAILURE = "DELETE_FARM_FAILURE";

export const DELETE_PUMP_START = "DELETE_PUMP_START";
export const DELETE_PUMP_SUCCESS = "DELETE_PUMP_SUCCESS";
export const DELETE_PUMP_FAILURE = "DELETE_PUMP_FAILURE";

export const DELETE_VALVE_START = "DELETE_VALVE_START";
export const DELETE_VALVE_SUCCESS = "DELETE_VALVE_SUCCESS";
export const DELETE_VALVE_FAILURE = "DELETE_VALVE_FAILURE";