export const FETCH_VALVE_START = "FETCH_VALVE_START";
export const FETCH_VALVE_SUCCESS = "FETCH_VALVE_SUCCESS";
export const FETCH_VALVE_FAILURE = "FETCH_VALVE_FAILURE";

export const ADD_VALVE_START = "ADD_VALVE_START";
export const ADD_VALVE_SUCCESS = "ADD_VALVE_SUCCESS";
export const ADD_VALVE_FAILURE = "ADD_VALVE_FAILURE";

export const UPDATE_VALVE_START = "UPDATE_VALVE_START";
export const UPDATE_VALVE_SUCCESS = "UPDATE_VALVE_SUCCESS";
export const UPDATE_VALVE_FAILURE = "UPDATE_VALVE_FAILURE";

export const DELETE_VALVE_START = "DELETE_VALVE_START";
export const DELETE_VALVE_SUCCESS = "DELETE_VALVE_SUCCESS";
export const DELETE_VALVE_FAILURE = "DELETE_VALVE_FAILURE";