// EXPORT ACTION TYPES

// ON LOGIN
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const FETCH_USER_DATA_START = "FETCH_USER_DATA_START";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";



// ADD RESOURCE
export const POST_FARM_START = "POST_FARM_START";
export const POST_FARM_SUCCESS = "POST_FARM_SUCCESS";
export const POST_FARM_FAILURE = "POST_FARM_FAILURE";

export const POST_PUMP_START = "POST_PUMP_START";
export const POST_PUMP_SUCCESS = "POST_PUMP_SUCCESS";
export const POST_PUMP_FAILURE = "POST_PUMP_FAILURE";

export const POST_VALVE_START = "POST_VALVE_START";
export const POST_VALVE_SUCCESS = "POST_VALVE_SUCCESS";
export const POST_VALVE_FAILURE = "POST_VALVE_FAILURE";

export const POST_STRATEGY_START = "POST_STRATEGY_START";
export const POST_STRATEGY_SUCCESS = "POST_STRATEGY_SUCCESS";
export const POST_STRATEGY_FAILURE = "POST_STRATEGY_FAILURE";

export const POST_TACTIC_START = "POST_TACTIC_START";
export const POST_TACTIC_SUCCESS = "POST_TACTIC_SUCCESS";
export const POST_TACTIC_FAILURE = "POST_TACTIC_FAILURE";

