// GET
export const FETCH_STRATEGY_START = "FETCH_STRATEGY_START";
export const FETCH_STRATEGY_SUCCESS = "FETCH_STRATEGY_SUCCESS";
export const FETCH_STRATEGY_FAILURE = "FETCH_STRATEGY_FAILURE";

export const FETCH_TACTIC_START = "FETCH_TACTIC_START";
export const FETCH_TACTIC_SUCCESS = "FETCH_TACTIC_SUCCESS";
export const FETCH_TACTIC_FAILURE = "FETCH_TACTIC_FAILURE";

// POST
export const POST_STRATEGY_START = "POST_STRATEGY_START";
export const POST_STRATEGY_SUCCESS = "POST_STRATEGY_SUCCESS";
export const POST_STRATEGY_FAILURE = "POST_STRATEGY_FAILURE";

export const POST_TACTIC_START = "POST_TACTIC_START";
export const POST_TACTIC_SUCCESS = "POST_TACTIC_SUCCESS";
export const POST_TACTIC_FAILURE = "POST_TACTIC_FAILURE";

// PUT
export const UPDATE_STRATEGY_START = "UPDATE_STRATEGY_START";
export const UPDATE_STRATEGY_SUCCESS = "UPDATE_STRATEGY_SUCCESS";
export const UPDATE_STRATEGY_FAILURE = "UPDATE_STRATEGY_FAILURE";

export const UPDATE_TACTIC_START = "UPDATE_TACTIC_START";
export const UPDATE_TACTIC_SUCCESS = "UPDATE_TACTIC_SUCCESS";
export const UPDATE_TACTIC_FAILURE = "UPDATE_TACTIC_FAILURE";

// DELETE
export const DELETE_STRATEGY_START = "DELETE_STRATEGY_START";
export const DELETE_STRATEGY_SUCCESS = "DELETE_STRATEGY_SUCCESS";
export const DELETE_STRATEGY_FAILURE = "DELETE_STRATEGY_FAILURE";

export const DELETE_TACTIC_START = "DELETE_TACTIC_START";
export const DELETE_TACTIC_SUCCESS = "DELETE_TACTIC_SUCCESS";
export const DELETE_TACTIC_FAILURE = "DELETE_TACTIC_FAILURE";