// GET
export const FETCH_PUMP_START = "FETCH_PUMP_START";
export const FETCH_PUMP_SUCCESS = "FETCH_PUMP_SUCCESS";
export const FETCH_PUMP_FAILURE = "FETCH_PUMP_FAILURE";

// ADD
export const ADD_PUMP_START = "ADD_PUMP_START";
export const ADD_PUMP_SUCCESS = "ADD_PUMP_SUCCESS";
export const ADD_PUMP_FAILURE = "ADD_PUMP_FAILURE";

// PUT
export const UPDATE_PUMP_START = "UPDATE_PUMP_START";
export const UPDATE_PUMP_SUCCESS = "UPDATE_PUMP_SUCCESS";
export const UPDATE_PUMP_FAILURE = "UPDATE_PUMP_FAILURE";

// DELETE
export const DELETE_PUMP_START = "DELETE_PUMP_START";
export const DELETE_PUMP_SUCCESS = "DELETE_PUMP_SUCCESS";
export const DELETE_PUMP_FAILURE = "DELETE_PUMP_FAILURE";

// ASSIGN STRATEGY
export const ASSIGN_STRATEGY_START = "ASSIGN_STRATEGY_START";
export const ASSIGN_STRATEGY_SUCCESS = "ASSIGN_STRATEGY_SUCCESS";
export const ASSIGN_STRATEGY_FAILURE = "ASSIGN_STRATEGY_FAILURE";