export const FETCH_FARM_START = "FETCH_FARM_START";
export const FETCH_FARM_SUCCESS = "FETCH_FARM_SUCCESS";
export const FETCH_FARM_FAILURE = "FETCH_FARM_FAILURE";

export const ADD_FARM_START = "ADD_FARM_START";
export const ADD_FARM_SUCCESS = "ADD_FARM_SUCCESS";
export const ADD_FARM_FAILURE = "ADD_FARM_FAILURE";

export const UPDATE_FARM_START = "UPDATE_FARM_START";
export const UPDATE_FARM_SUCCESS = "UPDATE_FARM_SUCCESS";
export const UPDATE_FARM_FAILURE = "UPDATE_FARM_FAILURE";

export const DELETE_FARM_START = "DELETE_FARM_START";
export const DELETE_FARM_SUCCESS = "DELETE_FARM_SUCCESS";
export const DELETE_FARM_FAILURE = "DELETE_FARM_FAILURE";