// GET
export const FETCH_TACTIC_START = "FETCH_TACTIC_START";
export const FETCH_TACTIC_SUCCESS = "FETCH_TACTIC_SUCCESS";
export const FETCH_TACTIC_FAILURE = "FETCH_TACTIC_FAILURE";

// ADD
export const ADD_TACTIC_START = "ADD_TACTIC_START";
export const ADD_TACTIC_SUCCESS = "ADD_TACTIC_SUCCESS";
export const ADD_TACTIC_FAILURE = "ADD_TACTIC_FAILURE";

// PUT
export const UPDATE_TACTIC_START = "UPDATE_TACTIC_START";
export const UPDATE_TACTIC_SUCCESS = "UPDATE_TACTIC_SUCCESS";
export const UPDATE_TACTIC_FAILURE = "UPDATE_TACTIC_FAILURE";

// DELETE
export const DELETE_TACTIC_START = "DELETE_TACTIC_START";
export const DELETE_TACTIC_SUCCESS = "DELETE_TACTIC_SUCCESS";
export const DELETE_TACTIC_FAILURE = "DELETE_TACTIC_FAILURE";